language: php

notifications:
  email:
    on_success: never
    on_failure: change

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
    - WP_CLI_CONFIG_PATH=/tmp/wp-cli-phar/config.yml

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.4
    - php: 5.6
      env: WP_VERSION=latest

install:
    - composer self-update && composer --version
    - composer install --no-interaction --prefer-source
    - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - bash bin/install-cli-tests.sh

script: ./ci/test.sh

after_script:
  - bash bin/upload-coverage.sh

addons:
    code_climate:
        repo_token: e9acdd855fa95cecc87ae5cdb1e329a9a78d97138d0f05f66c45ad86fb215f91
